
server:
  port: 0

spring:
  application:
    name: user-service
  jpa:
    ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: true

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1
    password: ''

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/develop?characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: 1234
#    url: jdbc:mariadb://database-1.cdod462vkjte.ap-northeast-2.rds.amazonaws.com:3306/develop?characterEncoding=UTF-8&serverTimezone=UTC
#    username: admin
#    password: qwer1234

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    com.example.userservice: DEBUG

token:
  access_expiration_time: 86400000
  #  1day
  refresh_expiration_time: 864000000
  secret: user_token